### ISSUE TITLE
HOW TO USE?

### ISSUE THREAD

**Issue by cardanawandra** [RUEEE/th19E-cheap-pvp#1]
HOW TO USE?

**Comment by RUEEE** [comment]
it's only for th19 trial ver(1.00a) since zun didn't make VS mode at that time. Now it's almost useless...
if you want to see the readme and release version at that time, here's a translated one->
https://files.williewillus.net/games/th19_netplay/udoalgnetplay-20230519.zip (by williewillus in ZUNCode discord
